apiVersion: v1
kind: PersistentVolume
metadata:
  name: movies
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 2Ti
  csi:
    driver: nfs.csi.k8s.io
    volumeAttributes:
      server: 10.0.0.21
      share: /mnt/data/media
      subdir: movies
    volumeHandle: 10.0.0.21#mnt/data/media#movies##
  mountOptions:
    - nfsvers=4.1
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-media
  volumeMode: Filesystem
