apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-nfs-driver
spec:
  interval: 30m
  chart:
    spec:
      chart: csi-driver-nfs
      version: "4.12.1"
      sourceRef:
        kind: HelmRepository
        name: csi-driver-nfs
      interval: 12h
  values:
    controller:
      replicas: 1
      runOnControlPlane: true
    storageClasses:
      - name: nfs-delete
        annotations:
          storageclass.kubernetes.io/is-default-class: "true"
        parameters:
          server: "10.0.0.21"
          share: /mnt/data/csi/delete
        reclaimPolicy: Delete
        volumeBindingMode: Immediate
        mountOptions:
          - nfsvers=4.1
      - name: nfs-retain
        parameters:
          server: "10.0.0.21"
          share: /mnt/data/csi/retain
        reclaimPolicy: Retain
        volumeBindingMode: Immediate
        mountOptions:
          - nfsvers=4.1