apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: matter-server
spec:
  storageClassName: nfs-named
  volumeName: matter-server-data
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
