apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: matter-server
spec:
  serviceName: matter-server
  replicas: 1
  selector: {}
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: |
          [{
            "name": "matter-static-net",
            "mac": "02:10:00:fa:01:03",
            "ips": [
              "10.0.0.63/24",
              "2a02:810d:bd90:bd00::63/64",
              "fd00:10::63/64"
            ]
          }]
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: matter-server
      containers:
        - name: matter-server
          image: ghcr.io/home-assistant-libs/python-matter-server:stable
          args:
            - --storage-path=/data
            - --paa-root-cert-dir=/data/credentials
            - --primary-interface=net1
          ports:
            - containerPort: 5580
              name: matter
          volumeMounts:
            - name: data
              mountPath: /data
          env:
            - name: STORAGE_PATH
              value: /data