apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cni-plugins-installer
spec:
  selector: {}
  template:
    spec:
      hostNetwork: true
      hostPID: true
      containers:
        - name: install-cni
          image: alpine:3.20
          securityContext:
            privileged: true
          command:
            - sh
            - -c
            - |
              set -e
              
              ARCH=$(uname -m)
              case "$ARCH" in
              x86_64)  ARCH=amd64 ;;
              aarch64) ARCH=arm64 ;;
              *) echo "Unsupported arch: $ARCH"; exit 1 ;;
              esac
              
              wget -qO /tmp/cni.tgz \
              https://github.com/containernetworking/plugins/releases/download/v1.9.0/cni-plugins-linux-${ARCH}-v1.9.0.tgz
              
              tar -xzf /tmp/cni.tgz -C /host/opt/cni/bin
              echo "CNI plugins installed/updated"
              
              sleep infinity
          volumeMounts:
            - name: cni-bin
              mountPath: /host/opt/cni/bin
      volumes:
        - name: cni-bin
          hostPath:
            path: /var/lib/rancher/k3s/data/cni
            type: Directory