apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
spec:
  interval: 30m
  chart:
    spec:
      chart: ingress-nginx
      version: "4.11.4"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: ingress-dmz
      interval: 12h
  values:
    nameOverride: "ingress-controller"
    fullnameOverride: "ingress-controller"
    controller:
      replicaCount: 1
      updateStrategy:
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: 0
          maxSurge: 1
      config:
        large-client-header-buffers: "8 64k"
        grpc-buffer-size-kb: "16384"
        custom-http-errors: "404,500,502,503,504"
      ingressClassResource:
        name: "dmz-ingress"
        enabled: true
      extraArgs:
        default-ssl-certificate: "$(POD_NAMESPACE)/default-cert"
      service:
        annotations:
          metallb.universe.tf/address-pool: "dmz-pool"
          metallb.universe.tf/loadBalancerIPs: "192.168.90.150"
    defaultBackend:
      enabled: true
      image:
        image: ingress-nginx/custom-error-pages
        tag: v1.2.4
        pullPolicy: IfNotPresent
      replicaCount: 1
      updateStrategy:
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: 0
          maxSurge: 1
      port: 8080
      extraEnv:
        - name: DEBUG
          value: "true"
      extraVolumes:
        - name: 404-page
          configMap:
            name: 404-html
            defaultMode: 420
        - name: 50x-page
          configMap:
            name: 50x-html
            defaultMode: 420
      extraVolumeMounts:
        - name: 404-page
          mountPath: /www/404.html
          subPath: index.html
        - name: 50x-page
          mountPath: /www/503.html
          subPath: index.html
