apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flannel
spec:
  interval: 30m
  chart:
    spec:
      chart: flannel
      version: "v0.27.4"
      sourceRef:
        kind: HelmRepository
        name: flannel
      interval: 1h
  values:
    podCidr: "172.16.0.0/16"


