apiVersion: v1
kind: Secret
metadata:
    name: redis-password
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:p0kpArvpClNM5boxFa2fh+JPffphgQEZ,iv:1QSSJs0gKZ0kSSYNhea61HiiRTKS57g0YgsmBnMVi7M=,tag:66e9c5Vy5BVLNR0neashqg==,type:str]
sops:
    age:
        - recipient: age1cl4m8gptnm0vm4g53x05fnn2r82u8hvdatkx07uheky4z7q7ef7sukrmwl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqMXZlRS83VTk1bWp0OGts
            bWZkdXJPZFNLaEswT3FURno2NWZ6YW5vWVJVCm9XVnhtK3RybXU5bjI1N2xtbjJZ
            N3J0M29VYUZSYk5oeDRPUExWdHlHWDgKLS0tIHJsUE5iNzZYT0NDNHYxWkl1ZVBG
            aWJHVWRlVFExMTFyRHZ4dU5TazF6Z2MKjkMHHxbFUIoK7s3jNfSdZ/B05Q/pSHa7
            V6oOSq05sct9xxUjncsC/zcc9NgB9h9exPvAMbXrUZWpNwYKzFM7bw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-20T17:29:53Z"
    mac: ENC[AES256_GCM,data:y/xuwfe785kaQRZfkIMvKFKWm+GJSlfUNUufKkmumMNOHdS/smYDBXpifKG6jDa5sPhLD6pGZ5pOP90im37OR/R9Q86WH+1Hez3VEuplCiEcwrvPpVsfPq5QMu7sR8BXZ3Im1FDgCEzYqkzV87nCSr2sw1vOVmC8sYTMOp0/pHM=,iv:aG1gfEB0V8HXnZ7CjDrgo0W7YPOVSlgG4Qju2+u5J78=,tag:F+D7sguh3C2HzYb4Ti1IPQ==,type:str]
    encrypted_regex: ^(data|stringData|email)$
    version: 3.10.2
