apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudnative-pg
spec:
  interval: 30m
  chart:
    spec:
      chart: cloudnative-pg
      version: "v0.26.1"
      sourceRef:
        kind: HelmRepository
        name: cnpg
      interval: 1h
  values:
    replicaCount: 1
    crds:
      create: true
    updateStrategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1


