apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: otbr-static-net
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "type": "ipvlan",
      "master": "eth0",
      "ipam": {
        "type": "static",
        "routes": [
          { "dst": "10.0.0.0/24", "gw": "10.0.0.1" },
          { "dst": "2a02:810d:bd90:bd00::/64", "gw": "2a02:810d:bd90:bd00::1" },
          { "dst": "fd00:10::/64", "gw": "fd00:10::1" }
        ]
      }
    }