apiVersion: v1
kind: PersistentVolume
metadata:
  name: otbr-data
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  csi:
    driver: nfs.csi.k8s.io
    volumeAttributes:
      server: 10.0.0.21
      share: /mnt/data/csi/named
      subdir: open-thread-border-router
    volumeHandle: 10.0.0.21#mnt/data/csi/named#open-thread-border-router##
  mountOptions:
    - nfsvers=4.1
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-named
  volumeMode: Filesystem
