apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: otbr-data
spec:
  storageClassName: nfs-named
  volumeName: otbr-data
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
