apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: otbr
spec:
  serviceName: otbr
  replicas: 1
  selector: {}
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: |
          [{
            "name": "otbr-static-net",
            "mac": "02:10:00:fa:01:04",
            "ips": [
              "10.0.0.64/24",
              "2a02:810d:bd90:bd00::64/64",
              "fd00:10::64/64"
            ]
          }]
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: otbr-data
      containers:
        - name: otbr
          image: openthread/border-router:latest
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
          env:
            - name: OT_RCP_DEVICE
              value: "spinel+hdlc+uart:///dev/ttyACM0?uart-baudrate=1000000"
            - name: OT_INFRA_IF
              value: "eth1"
            - name: OT_THREAD_IF
              value: "eth1"
            - name: OT_LOG_LEVEL
              value: "7"
          ports:
            - containerPort: 8081
              name: otbr-rest
            - containerPort: 5353
              name: mdns
              protocol: UDP
          volumeMounts:
            - name: data
              mountPath: /data