apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: otbr
spec:
  serviceName: otbr
  replicas: 1
  selector: {}
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: |
          [{
            "name": "otbr-static-net",
            "mac": "02:10:00:fa:01:04",
            "ips": [
              "10.0.0.64/24",
              "2a02:810d:bd90:bd00::64/64",
              "fd00:10::64/64"
            ]
          }]
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: otbr-data
      containers:
        - name: otbr
          image: ghcr.io/ownbee/hass-otbr-docker
          env:
            - name: "DEVICE"
              value: "/dev/ttyUSB1"
            - name: "BACKBONE_IF"
              value: "eth1"
            - name: "FLOW_CONTROL"
              value: "1"
            - name: "FIREWALL"
              value: "1"
            - name: "NAT64"
              value: "1"
            - name: "BAUDRATE"
              value: "460800"
            - name: "OTBR_REST_PORT"
              value: "8081"
            - name: "OTBR_WEB_PORT"
              value: "8080"
            - name: "AUTOFLASH_FIRMWARE"
              value: "0"
          ports:
            - containerPort: 8081
              name: rest
            - containerPort: 8080
              name: web
          volumeMounts:
            - name: data
              mountPath: /var/lib/thread