apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: hass-static-net
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "type": "ipvlan",
      "master": "eth0",
      "ipam": {
        "type": "static",
        "routes": [
          {"dst": "10.0.0.0/24", "gw": "10.0.0.1"}
        ]
      }
    }