apiVersion: v1
kind: PersistentVolume
metadata:
  name: home-assistant-config
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Gi
  csi:
    driver: nfs.csi.k8s.io
    volumeAttributes:
      server: 10.0.0.21
      share: /mnt/data/csi/named
      subdir: home-assistant
    volumeHandle: 10.0.0.21#mnt/data/csi/named#home-assistant##
  mountOptions:
    - nfsvers=4.1
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-named
  volumeMode: Filesystem
