apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ha-config
spec:
  storageClassName: nfs-named
  volumeName: home-assistant-config
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
