apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: home-assistant
spec:
  serviceName: home-assistant
  replicas: 0
  updateStrategy:
    type: OnDelete
  selector: {}
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: |
          [{
            "name": "hass-static-net",
            "mac": "02:10:00:fa:01:02",
            "ips": ["10.0.0.62/24"]
          }]
    spec:
      terminationGracePeriodSeconds: 60
      volumes:
        - name: ha-config
          persistentVolumeClaim:
            claimName: ha-config
        - name: localtime
          hostPath:
            path: /etc/localtime
      containers:
        - name: home-assistant
          image: ghcr.io/home-assistant/home-assistant:stable
          imagePullPolicy: Always
          volumeMounts:
            - name: ha-config
              mountPath: /config
            - name: localtime
              mountPath: /etc/localtime
              readOnly: true
          ports:
            - containerPort: 8123
              name: http