apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: music-assistant-data
spec:
  storageClassName: nfs-retain
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
