apiVersion: v1
kind: PersistentVolume
metadata:
  name: paperless-ngx-consume
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Gi
  csi:
    driver: nfs.csi.k8s.io
    volumeAttributes:
      server: 10.0.0.21
      share: /mnt/data/csi/named
      subdir: paperless-ngx/consume
    volumeHandle: 10.0.0.21#mnt/data/csi/named#paperless-ngx/consume##
  mountOptions:
    - nfsvers=4.1
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-named
  volumeMode: Filesystem
