apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-ngx-consume
spec:
  storageClassName: nfs-named
  volumeName: paperless-ngx-consume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
