apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-ngx-media
spec:
  storageClassName: nfs-named
  volumeName: paperless-ngx-media
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
