apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-godaddy
spec:
  acme:
    email: you@example.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-godaddy-key
    solvers:
      - dns01:
          webhook:
            groupName: golocal.dev
            solverName: godaddy
            config:
              apiKeySecretRef:
                name: godaddy-dns
                key: api-key
              apiSecretSecretRef:
                name: godaddy-dns
                key: api-secret