apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: music
spec:
  storageClassName: nfs-media
  volumeName: music
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 2Ti