apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: movies
spec:
  storageClassName: nfs-media
  volumeName: movies
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 2Ti