apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: default-ingress-cert
spec:
  secretName: default-cert
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-cloudflare
  commonName: golocal.dev
  dnsNames:
    - golocal.dev
    - info.golocal.dev