apiVersion: v1
kind: Secret
metadata:
    name: wg-easy-password
type: Opaque
stringData:
    PASSWORD_HASH: ENC[AES256_GCM,data:DjnCM0Lwt3mClysSufGd806v53zwVaEouNaU46K1oL/8hm6jarseBgnrEfSsrE6lmYj8pUNs3ogqruLG,iv:9aqpBZkqytfBrfNpAexhyPYD2GqD743V/C6oyOmQCR8=,tag:LNqIkn6oL15L3OAbtf9n5A==,type:str]
sops:
    age:
        - recipient: age1cl4m8gptnm0vm4g53x05fnn2r82u8hvdatkx07uheky4z7q7ef7sukrmwl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhRWVNMHJ1MXFoYU55blg5
            anduTVNvNEduRlg3cmZITjFjQjRJZUtITUdRCm1iS0pzQUJqL0QvYktOWGI3WGVv
            QTB3SW13ZktjcEhFdjlERG9nZ00zNlEKLS0tIEs0MUJJeTFvV2pWSkk0MHN1RDA0
            UEMyUi9oS0lObzNKZTRTdkxXSmxVbVUKVXK+LmW2EERhGx/gsfq4FzYR4eACiRhP
            r7j8Z1QpX7ag5d2Fc48Oa2FddW7uHphSoRK53lYXmyB8Z7PH4GQ40Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-18T23:10:37Z"
    mac: ENC[AES256_GCM,data:OuWhAPBSPjIPAMzw6d8uPB9TQCW3niXG9634EgwVXwokCRCEujpAARt0l59/JZOFCU2VuVWm1mp2yAsqShO6N4AC+UKHx0jgjdKyeLjVRIF3BjImziWoaxVE8KSwWdM/xlyKfwwWV51qy8zMdjHhcBZYH9hpOXEu3+UonJPF4h8=,iv:xygcuI2b4kZsyMV37X2hIngUt6MaO5Smg3Q4TY8kz0Y=,tag:QsXnNdIZhbdrUuF1vfkphQ==,type:str]
    encrypted_regex: ^(data|stringData|email)$
    version: 3.10.2
