apiVersion: v1
kind: Service
metadata:
  name: wg-easy-wg
  annotations:
    metallb.universe.tf/address-pool: "dmz-pool"
    metallb.universe.tf/loadBalancerIPs: "10.0.0.56"
spec:
  type: LoadBalancer
  ports:
    - name: wg
      port: 51976
      protocol: UDP
      targetPort: wg
